name: build-tables-wheel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Prep build environment
        run: |
          python -m pip install -U pip setuptools wheel cython "numpy<2"

      - name: Build tables wheel
        run: |
          python -m pip wheel tables==3.7.0 --no-deps -w dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: tables-wheel
          path: dist\*.whl
          if-no-files-found: error
